[package]
name = "larps"
version = "0.1.0"
authors = ["Brett Haines <brett@hainescoding.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
log = "0.4"
regex = "1"

[dependencies.async-std]
version = "1.9"
features = ["attributes"]

[dependencies.simple_logger]
version = "1.11"